name: data_visualization_binder
channels:
  - conda-forge
  - default
dependencies:
  - jupytext
  - jupyterlab>=3
  - ipywidgets>=7.6
  - python
  - numpy
  - matplotlib-base
  - ipympl
  - pandas
  - openpyxl
  - seaborn
  - plotly
  - scikit-learn